spring:
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://localhost:27017/resolution
logging.level:
  org.springframework.data.mongodb.coreMongoTemplate: DEBUG
#  reactor.core.publisher: INFO