spring:
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/resoultion
  thymeleaf:
    cache: false
logging.level:
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
#  reactor.core.publisher: INFO