version: '3'

services:
  mongodb:
    image: mongo
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=resolution
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017